name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: start docker
        run: docker-compose up -d    
      - name: testa front 
        run: docker exec gerencia-trabalho_frontend_1 sh -c "CI=false npm run test"
      - name: testa back
        run: docker exec gerencia-trabalho_backend_1 sh -c "python3 manane.py test"
